name: .NET Selenium Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore --source "https://api.nuget.org/v3/index.json" --source "https://github.com/BenSella/c-sharp-selenuum-alure-solution/tree/main/SeleniumAutomationLibrary/bin/Debug"

    # Step 4: Build the project
    - name: Build
      run: dotnet build --configuration Release

    # Step 5: Run tests and check JSON modifications
    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=TestResults.trx"

    # Step 6: Display the updated caching file (if updated)
    - name: Show updated caching data
      run: cat MagentoSelenuimAutomationDemo/cachingData.json

    # Step 7: (Optional) Push updated JSON file back to the repo
    - name: Commit and push changes
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add MagentoSelenuimAutomationDemo/cachingData.json
        git commit -m "Update caching data after test run"
        git push https://github-actions:${GITHUB_TOKEN}@github.com/BenSella/c-sharp-selenuum-alure-solution.git